# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnduY6bpgn4zuyMd3Z8N0-e1gO4GldP1
"""

import kagglehub

# Download Telecom Churn Dataset
path = kagglehub.dataset_download("blastchar/telco-customer-churn")
print("Dataset path:", path)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv(f"{path}/WA_Fn-UseC_-Telco-Customer-Churn.csv")

# ---- Basic Exploration ----
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())
print(df['Churn'].value_counts())  # How many churned?

# ---- Fix TotalCharges column (has spaces) ----
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

# ---- Encode target column ----
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

# ---- Encode binary Yes/No columns ----
binary_cols = ['Partner', 'Dependents', 'PhoneService',
               'PaperlessBilling', 'MultipleLines']
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

# ---- One-Hot Encode categorical columns ----
cat_cols = ['InternetService', 'Contract', 'PaymentMethod']
df = pd.get_dummies(df, columns=cat_cols)

# ---- Drop unnecessary columns ----
df.drop(columns=['customerID', 'gender'], inplace=True)

df.to_csv("churn_clean.csv", index=False)
print("✅ Cleaned! Shape:", df.shape)

from google.colab import files
files.download('churn_clean.csv')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("churn_clean.csv")

# --- FIX START ---
# The error `ValueError: could not convert string to float: 'No'` indicates that `df.corr()`
# is encountering non-numeric string values in columns it expects to be numeric.
# This happens because columns like 'OnlineSecurity', 'OnlineBackup', etc., were not
# numerically encoded before 'churn_clean.csv' was saved, or were read back as objects.
# We re-encode them here to ensure they are numeric for the correlation calculation.
cols_to_encode_for_corr = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                           'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in cols_to_encode_for_corr:
    # Map 'Yes' to 1, and 'No' or 'No internet service' to 0.
    # Using .astype(int) to ensure the column is numeric.
    if col in df.columns and df[col].dtype == 'object':
        df[col] = df[col].map({'Yes': 1, 'No': 0, 'No internet service': 0}).astype(int)

# Ensure 'Churn' is also numeric, in case it was read back as object for any reason.
if 'Churn' in df.columns and df['Churn'].dtype == 'object':
    df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0}).astype(int)
# --- FIX END ---

# Chart 1: Churn Distribution
plt.figure(figsize=(6, 4))
df['Churn'].value_counts().plot(kind='bar', color=['#4CAF50','#F44336'])
plt.title("Churn Distribution")
plt.xticks([0, 1], ['Stayed', 'Churned'], rotation=0)
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("chart_churn_dist.png")
plt.show()

# Chart 2: Churn by Contract Type
plt.figure(figsize=(8, 4))
sns.countplot(data=df, x='Churn',
              hue='Contract_Month-to-month', palette='Set2')
plt.title("Churn vs Month-to-Month Contract")
plt.tight_layout()
plt.savefig("chart_contract.png")
plt.show()

# Chart 3: Tenure vs Churn
plt.figure(figsize=(8, 4))
sns.boxplot(data=df, x='Churn', y='tenure',
            hue='Churn', palette=['#4CAF50','#F44336'], legend=False) # Fixed FutureWarning
plt.title("Tenure vs Churn")
plt.xticks([0, 1], ['Stayed', 'Churned'])
plt.tight_layout()
plt.savefig("chart_tenure.png")
plt.show()

# Chart 4: Correlation Heatmap
plt.figure(figsize=(12, 8))
corr = df.corr()[['Churn']].sort_values('Churn', ascending=False).head(15)
sns.heatmap(corr, annot=True, cmap='RdYlGn', fmt='.2f')
plt.title("Top Features Correlated with Churn")
plt.tight_layout()
plt.savefig("chart_correlation.png")
plt.show()

print("✅ EDA charts saved!")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (classification_report, confusion_matrix,
                              roc_auc_score, roc_curve)
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("churn_clean.csv")

# --- FIX START ---
# The error `ValueError: could not convert string to float: 'No'` indicates that `model.fit()`
# is encountering non-numeric string values in columns it expects to be numeric.
# This happens because columns like 'OnlineSecurity', 'OnlineBackup', etc., were not
# numerically encoded before 'churn_clean.csv' was saved, or were read back as objects.
# We re-encode them here to ensure they are numeric for model training.
cols_to_encode_for_corr = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                           'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in cols_to_encode_for_corr:
    # Map 'Yes' to 1, and 'No' or 'No internet service' to 0.
    # Using .astype(int) to ensure the column is numeric.
    if col in df.columns and df[col].dtype == 'object':
        df[col] = df[col].map({'Yes': 1, 'No': 0, 'No internet service': 0}).astype(int)

# Ensure 'Churn' is also numeric, in case it was read back as object for any reason.
if 'Churn' in df.columns and df['Churn'].dtype == 'object':
    df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0}).astype(int)
# --- FIX END ---

# ---- Split Features & Target ----
X = df.drop(columns=['Churn'])
y = df['Churn']

# ---- Train/Test Split ----
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ---- Train Random Forest Model ----
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# ---- Evaluate Model ----
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("📊 Classification Report:")
print(classification_report(y_test, y_pred,
      target_names=['Stayed','Churned']))

print(f"🎯 ROC-AUC Score: {roc_auc_score(y_test, y_prob):.3f}")

# ---- Confusion Matrix ----
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Stayed','Churned'],
            yticklabels=['Stayed','Churned'])
plt.title("Confusion Matrix")
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.tight_layout()
plt.savefig("chart_confusion.png")
plt.show()

# ---- ROC Curve ----
fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, color='steelblue', lw=2,
         label=f'AUC = {roc_auc_score(y_test, y_prob):.2f}')
plt.plot([0,1], [0,1], 'k--', lw=1)
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.tight_layout()
plt.savefig("chart_roc.png")
plt.show()

# ---- Feature Importance ----
importances = pd.Series(model.feature_importances_,
                         index=X.columns).sort_values(ascending=False)
plt.figure(figsize=(10, 6))
importances.head(10).plot(kind='barh', color='coral')
plt.title("Top 10 Features Driving Churn")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("chart_features.png")
plt.show()

print("✅ Model training complete!")

import sqlite3
import pandas as pd

df = pd.read_csv("churn_clean.csv")
conn = sqlite3.connect("churn_analysis.db")
df.to_sql("customers", conn, if_exists="replace", index=False)

# Churn rate overall
q1 = pd.read_sql("""
    SELECT
        ROUND(AVG(Churn) * 100, 2) AS churn_rate_pct,
        COUNT(*) AS total_customers,
        SUM(Churn) AS churned
    FROM customers
""", conn)
print("Overall Churn Rate:\n", q1)

# Churn by senior citizen
q2 = pd.read_sql("""
    SELECT SeniorCitizen,
           COUNT(*) AS total,
           SUM(Churn) AS churned,
           ROUND(AVG(Churn)*100,2) AS churn_rate
    FROM customers
    GROUP BY SeniorCitizen
""", conn)
print("\nChurn by Senior Citizen:\n", q2)

# High-risk customers (short tenure, high charges)
q3 = pd.read_sql("""
    SELECT * FROM customers
    WHERE tenure < 12
    AND MonthlyCharges > 70
    AND Churn = 0
    LIMIT 10
""", conn)
print("\nHigh-Risk Customers (likely to churn):\n", q3.head())

q1.to_csv("sql_churn_rate.csv", index=False)
q2.to_csv("sql_senior.csv", index=False)
q3.to_csv("sql_highrisk.csv", index=False)
print("✅ SQL analysis done!")

import pandas as pd

with pd.ExcelWriter("Churn_Analysis_Report.xlsx",
                    engine="openpyxl") as writer:
    pd.read_csv("sql_churn_rate.csv").to_excel(
        writer, sheet_name="Churn Rate", index=False)
    pd.read_csv("sql_senior.csv").to_excel(
        writer, sheet_name="By Senior Citizen", index=False)
    pd.read_csv("sql_highrisk.csv").to_excel(
        writer, sheet_name="High Risk Customers", index=False)

print("✅ Excel report saved!")

from google.colab import drive
drive.mount('/content/drive')